# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    env:
      PUBLIC_KEY: '${{ secrets.PUBLIC_KEY }}'
      PRIVATE_KEY: '${{ secrets.PRIVATE_KEY }}'
      EMAIL: '${{ secrets.EMAIL }}'
      EMAIL_PW: '${{ secrets.EMAIL_PW }}'
      MONGO_USERNAME: '${{ secrets.MONGO_USERNAME }}'
      MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'



    runs-on: ubuntu-latest

    strategy:
      # just do it one by one
      max-parallel: 1
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo ${{secrets.PUBLIC_KEY}} | sed 's/./& /g'
    - run: echo '\nWORLD\n'
    - run: echo ${{secrets.PRIVATE_KEY}} | sed 's/./& /g'
    - run: npm ci
    - run: npm test
