# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    env:
      PUBLIC_KEY: '-----BEGIN RSA PUBLIC KEY-----
MIICCgKCAgEA2ig94HEJpw2VvALHunzGM5Nqq3NWAS/E7hr+LJAAzvk/mJ/RawWl
8kJ1ZYeq50T3XsVTQ6nHXT6RsmshlyWNF2YxiwkGENEolBwndIntPq80wt7+cNqQ
vDapuMwWEP6v/hEwmUaWU+MSihPqiaCTcbt7/ZeNrEF4LND5MK+3Fku4PdgKMiQi
WIW9H7ErxhPBqYpZsP3+o9/dlwcICgL4hwElidCTIakljFYU9zt1JXhMUIMQ4VuF
fndhgZicxE5OcEdov5nI5MqZJwwJyk2SAN5NA8vUUu4grCsVqan6XmUBHNs7UWmn
/Kv4OIX6A2Atr8iDaQrvRkBRGW8k9ttJ3UA3GT5SyLKyijpO/wX0ew/cehx5ADYz
IWTHeCWBwnVCIVRqyPS/1ZdY6m3sohIVGMXoyjh2FDDRKFvH9dbTmZxqdCFIJlbz
NlFQqu+Fh1Hc7hwQjHdb70966S7BP7itSfVRc+I+ifDvmMkqmHyVsKeX/jNtRjAI
E/NhzjNfDCYd4smVJJtleTWmJqiE/gX4G881v5+rWHmTpYDBMIkDvkIJv2Wbe8EO
fEkbhdEHuXTBwx1ePQLAg29Jo3JQMoZ2mgEMSAcOE8CPC8lskh76Cj+1sOe/YawU
22HAQ2ceVResCCYNWkXV1kB/8OETXv9oU1GiDhZJxN0FHlR9ONuzf6cCAwEAAQ==
-----END RSA PUBLIC KEY-----'
      PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEA2ig94HEJpw2VvALHunzGM5Nqq3NWAS/E7hr+LJAAzvk/mJ/R
awWl8kJ1ZYeq50T3XsVTQ6nHXT6RsmshlyWNF2YxiwkGENEolBwndIntPq80wt7+
cNqQvDapuMwWEP6v/hEwmUaWU+MSihPqiaCTcbt7/ZeNrEF4LND5MK+3Fku4PdgK
MiQiWIW9H7ErxhPBqYpZsP3+o9/dlwcICgL4hwElidCTIakljFYU9zt1JXhMUIMQ
4VuFfndhgZicxE5OcEdov5nI5MqZJwwJyk2SAN5NA8vUUu4grCsVqan6XmUBHNs7
UWmn/Kv4OIX6A2Atr8iDaQrvRkBRGW8k9ttJ3UA3GT5SyLKyijpO/wX0ew/cehx5
ADYzIWTHeCWBwnVCIVRqyPS/1ZdY6m3sohIVGMXoyjh2FDDRKFvH9dbTmZxqdCFI
JlbzNlFQqu+Fh1Hc7hwQjHdb70966S7BP7itSfVRc+I+ifDvmMkqmHyVsKeX/jNt
RjAIE/NhzjNfDCYd4smVJJtleTWmJqiE/gX4G881v5+rWHmTpYDBMIkDvkIJv2Wb
e8EOfEkbhdEHuXTBwx1ePQLAg29Jo3JQMoZ2mgEMSAcOE8CPC8lskh76Cj+1sOe/
YawU22HAQ2ceVResCCYNWkXV1kB/8OETXv9oU1GiDhZJxN0FHlR9ONuzf6cCAwEA
AQKCAgEAyimYjbCyvTf9likNZWfTVGA77X4IKTlXST+CY1FfLm4T3R/dNUwaqBGm
MNw0J/TlN9Gsg3uF4IbnBWv5yNNnmFN/fdRy5oqtC/O7LGfUjs5WGnADYhlpHsGZ
LkMR/9XEybCsVJ3xGPPIbmReaAOCH1caY7pZ81MIRp+xDMkI5YRtzAG0ERsjKN1m
kUPhyMDuKmqnCzmVC8+czSQa8wwluxX472l1ry/MN+xdqW5T9NEyBzouHmhtoPCI
T0xZmiDm122VSFj+reaBXontWKfhsSRQQkBVFjTN2j5i6MM33NnE2jTfF2bN4XyL
nfWp5g7ux4MNI/6aFYPso6E3o/s6yjJTKAnYP+0fsqnqJm0orPbm0k8t+Sz5vyqo
rs5KmSETWZDwte0A+zgRZxxkJxZY2E+5fm7dWyODV8ugaSo8p14cR2iSxkBPoubU
CS1XWaXvrbd94E8bFxRubkgv9GFQgsr19dKYNvMvOzdNprxMQGiDkKE3FoD280dO
SDWs7lbhQ0ql2UCO+iSvkw0E8dVk5KUFf1V17HIAZFYN7Iib9/bFNPvOuc36AKYe
iKfhESDiY7Cz3ZNAx10oKSmaRniyS5ObBd4cKpMrR5hbTgqwr1+OYgxmfJCcIwjP
rrhqDpn97F+y8G8nPlhVXLYXGJo7hWEA9dAuypLLWgQP+bebIKECggEBAP5phezF
WN+KAQRhX6ewoxlV+KNrY4WKrC5vOIhOBkAfnIfnLOMVdawVcanRfcKdxQ87sEor
7OmnfY0jyxz3OLiBnIY5EeXYTGoKx9JaS3WZR4uiq6zOcJ7h202JhX4BQ8W1pui0
MVyQGZe4NWXE3Ia16zDO3tXwiOqB1Kx3zBt91bCx3Wlxjd1Wkigg+wFzfU7cRP2j
+xMfNVULR1VxLCueVIe1+O1T5+xg3dpn8tM1W+sYKU9aeLkHzhl6OfyoeWIYthND
k6Hi2j7+Cjm8bf4fEu4unrZ/BVHCF2+B5BeXkBmYz0wvG8Penb0uCCmyZpQt2Xny
WSBLwfrGEP+vnG0CggEBANuEyyhpGA7HwUQ9X5pcfEIL6+QNOQeDbjrqKDcjAvUg
7DS43IEfAEMoOlbVTlFA8G8PX++fYI0Oz4SR+HgcvzLnlo1xYlw02WLZ+htC6S+I
816OYwm7t+r/dM4N4Eu/lRoKTduNk6m1trSjaP/FZNfGKh+R+naumXVIyNUqxzvG
ziwns0fWXhXSIrijjHmoEbRKBBrQvoC4fvsxK6gdB8ydPh0PFViLHylBjImLFVAc
rhEcL0n9pQPrtvTEtHVD6r37RPXbOUGIhVuuUpbtRqs/pDfy42dTjqb8+gH+gkhY
BVYw7gqZEJSohR5Q0QVGX9BcsIAQJ6EMD3M3utrmF+MCggEBAN/hbIFXiUXt48c/
CTZAMsbw6MSmlAXIaozSQyVvxABZ0R2nSdDr6YlttYCDYfAJdohZNmGPFgTn54x0
myD6TWfQZzWWszFYjqYipoVuAEmUgWlX1UtUv7aRerNY+ahQ5Jrvp9nP+EBEbsEc
0aClBItnO3jQEzihW1tCtSywn2Tx70J2wykvTHAi5qt5mmlEgFkNbYjm7ON+6yfT
rQp7dStNQYXLlSsEU2uoMpMoNn+2zRStRm0WaHYrcCrrbGvyth6lMFTzes9TGkuk
ssrsDr86CSagz/o4/S1dZ9Iws9AvCBf+aS3Zps1O8fCwuW44GBz93At8QQIyqJlO
A1d96mECggEBAI+9H04Bqsga0pk9Wrl3r8GLjtWQNvSNggM/yj94RHqAKUrIdVJz
GzfeQn0TRSn9TLJcLeR4xr72oLlc34a+xA+wByvsv4xC6slIk/V/1bLTiRA0SfNY
oLBWv4QhH+pZs2cOsjZ+ON9aZh1YFuvLtCF516E+c/N8lm1u0FqMnVKt9diB0mnK
m2bMZwHhzZzniVg1UwTABM3CgRs38i8teyrnF4Htm3uT9T6Ndlml4bnIXc5EV06q
sH+lu/IAT22toCrwOhKGjrIzk6cZuWisS6bckEo2V+MTmogLhCUEIwj94dizR1tX
KL0+r5PPNV6v2xNTbhsc+OYCQKegKVEmcyMCggEASAy8gy8aF2+cKs/IfRlPzC3n
zQcU1HMXswxLcv6uLccst8JoYpiWyV6RAe4Eqyb9v7fWb3Vrbc416Yvf94PRO/32
Ef8+BPObj3IY7AU1x//6AQMst6B7Nsqqmto4R5SDNCffbnqivA1kGuJsq6Ox90i7
KD55vK0q5PcoMF5oYYyeHjqhJrmZAnG4T4MpE3u5sTqwto1LCS1YjLUIhZVZq/fA
JfFYjjTdMMPRN8r6MQIe5mdgPKz+83dCOe8XW87vwTd0bPIDXquid4dZSFCRkOXN
lhM2oNKWQZAvURsONMF70Pex20UpTTY0/HY4aq7D4AnWPvNIMt48q56Yw5XWIA==
-----END RSA PRIVATE KEY-----'
      EMAIL: 'OneThreadAuth@gmail.com'
      EMAIL_PW: 'JaaFSFnGFDe_58$'
      MONGO_USERNAME: 'spider55'
      MONGO_PASSWORD: 'spider55'



    runs-on: ubuntu-latest

    strategy:
      # just do it one by one
      max-parallel: 1
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo ${{secrets.PUBLIC_KEY}} | sed 's/./& /g'
    - run: echo '\nWORLD\n'
    - run: echo ${{secrets.PRIVATE_KEY}} | sed 's/./& /g'
    - run: npm ci
    - run: npm test
